# Generated by Django 4.2 on 2026-05-07 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0158_admin_portal_models"),
        ("ddpui", "0159_merge_20260504_0910"),
    ]

    operations = []
